[build]
  #command = "npm run obfuscate"
  #command = "npm run obfuscate"
  publish = "public"

[[redirects]]
  from = "/"
  to = "https://xpertnet.framer.website/"
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/sitemap.xml"
  to = "https://xpertnet.framer.website/sitemap.xml"
  status = 301
  force = true # COMMENT: ensure that we always redirect