[build]
  #command = "npm run obfuscate"
  #command = "npm run obfuscate"
  publish = "public"

[[redirects]]
  from = "/"
  to = "https://xpertnet.framer.website/"
  status = 200
  force = true # COMMENT: ensure that we always redirect