[build]
  #command = "npm run obfuscate"
  #command = "npm run obfuscate"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "https://contextual-times-650328.framer.app/"
  status = 200
  force = true # COMMENT: ensure that we always redirect