[build]
  #command = "npm run obfuscate"
  #command = "npm run obfuscate"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "https://xpertnet.framer.website/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/sitemap.xml"
  to = "https://xpertnet.framer.website/sitemap.xml"
  status = 200
  force = true # COMMENT: ensure that we always redirect